### ISSUE TITLE
Unhandled rejection TypeError: res.send(...).statusCode is not a function

### ISSUE THREAD

**Issue by fonzSJ** [CiccioTecchio/SharErasmus#19]
**Describe the bug**
Usando `res.statusCode(<codice HTTP>)`  viene generato l'errore: `Unhandled rejection TypeError: res.send(...).statusCode is not a function`

**To Reproduce**
1. Eseguire una query (sequelize) dove la bisogna settare lo statusHTTP.

**Expected behavior**
Mi aspettavo lo statusCode impostato, invece il codice HTTP restituito era 200.

**Comment by CiccioTecchio** [comment]
Per risolvere questo problema settare lo statusCode prima della send ad esempio
```js res.statusCode = 403
res.send(<oggetto da restituire>).end()
```
Per ulterio info consutare la [risposta su stackoverflow](https://stackoverflow.com/questions/10563644/how-to-specify-http-error-code).
