### ISSUE TITLE
Change Request DB

### ISSUE THREAD

**Issue by CiccioTecchio** [CiccioTecchio/SharErasmus#20]
Effettuare i seguenti cambiamenti al db:
- i nomi delle colonne vanno scritti in camelCase, così facendo rispetteranno i nomi descritti nei model
- aggiungere sia allo studente che al coordinatore la colonna **bio** e il la colonna **facolta**
- modificare il campo password definendo come **VARCHAR(64)**
- nella tabella **Post** aggiungere il campo **post** che contiene il corpo della post **VARCHAR(300)**.
- nella tabella **Post** e nel relativo model rendere l'**id_Post** un auto-incerement

P.S Al momento ci sono dei problemi con il db remoto di AWS, quindi effettua queste modifiche in locale dopodichè importa il db che hai modificato in locale su AWS RDS

**Comment by s-corso-98** [comment]
Apportate tutte le correzioni e committate.
