### ISSUE TITLE
How to upload an image in a img tag

### ISSUE THREAD

**Issue by s-corso-98** [CiccioTecchio/SharErasmus#26]
**Describe the bug**
Ottenere un'immagine dal database e caricarla nell'attributo src può risultare complicato tramite gli screen illustrerò come fare.

**How to**

1. 
 Fare la richiesta ajax al route dove si ottengono le informazioni dal database richieste
![help1](https://user-images.githubusercontent.com/44057901/50540369-e19efd00-0b90-11e9-93a1-064b4338f19a.PNG)

2.
A seconda delle proprie esigenze adattare il seguente codice. Help3 conterrà l'immagine ottenuta dal database tuttavia non è in un formato adatto da poter essere inserito direttamente in src. 
**n.b.** La mia gestione conteneva diversi tag img e diverse immagini ottenute dal database(array json) per cui ho dovuto utilizzare l'indice i per prendere l'i-esima immagine dal database (data[i]) e caricarla nell'i-esimo tag img (output[i]). 
![help2](https://user-images.githubusercontent.com/44057901/50540398-5eca7200-0b91-11e9-86e5-e25f1011f224.PNG)

Per qualsiasi dubbio contattatemi.

**Comment by CiccioTecchio** [comment]
Nota nel for loop non usare `length(data)`perchè questa è una chiamata a funzione messa in un ciclo quindi richiamerai length(data) volte la funzione length. Per porre rimedio a questo problema dichiarati una variabile alla quale assegniil risultato di lenght(data)
