### ISSUE TITLE
Rimozione index.js

### ISSUE THREAD

**Issue by CiccioTecchio** [CiccioTecchio/SharErasmus#28]
**Describe the bug**
Rimuovere index.js con le relative dipendenze presenti in app.js. Quel file serviva solo all'inizio per farvi vedere come funzionavano i router ora non è più necessario quindi eliminatelo anche perchè fa fallire i test di Travis-CI.

**Comment by CiccioTecchio** [comment]
@s-corso-98 la rimozione di index.js verrà fatta da @fonzSJ ho assegnato anche te su quest Issue per metterti a conoscenza di questo cambiamento dato che avevo notato un tuo commit su quel file.

**Comment by fonzSJ** [comment]
Ho eliminato il file index.js!
