### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by davide-bottiglieri** [CiccioTecchio/SharErasmus#31]
### Sviluppo
- [ ] client
- [X] server

### Ho sviluppato
- Inserimento post
- Visualizzazione post
- Inserimento risposta
- Visualizzazione risposta

### Devo ancora sviluppare
- Fissare post
- Certificazione profilo
- Visualizzazione post tramite tag
- Visualizzazione avvisi (bacheca a.)
- Inserimento avvisi (bacheca a.)
- Modifica voto (rating)

### Problemi incontrati
Sto avendo qualche problema con il fissaggio del post, per ridurre il numero di costrutti "if" avevo deciso di farlo tramite una query ma penso di dover cambiare approccio dato che non mi sta portando a nulla di concreto, inoltre vorrei avere alcune delucidazioni sull'upload dei file.

**Comment by CiccioTecchio** [comment]
Allora tu in particolare necessiti prima di un merge sul master in maniera tale da poter lavorare su una versiona più aggiornata del sistama. Quindi appena puoi fai una _pull request_ dopodichè revisiona il tuo codice in base agli aggiornamenti fatti. Per quanto riguarda l'upload dei file puoi chiedere anche a @fonzSJ
