### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by fonzSJ** [CiccioTecchio/SharErasmus#32]
### Sviluppo
- [ ] client
- [x] server

### Ho sviluppato
-  Registrazione alla piattaforma
-  Login alla piattaforma
-  Cancella account
-  Inserimento Bio
-  Visualizzazione dati di accesso
-  Modifica dati di accesso

### Devo ancora sviluppare
- Recupero della password

### Problemi incontrati
Sto avendo dei problemi ad implementare la funzionalità di recupero password, ma penso di essere sulla buona strada.
Vorrei ridurre il numero di 'if' dove possibile.

**Comment by CiccioTecchio** [comment]
Nel caso in cui tu non riesca a ridurre il numero di if allora cerca di aumentare i casi di test è la strada più rapida a volta.
