### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by peppeprown2** [CiccioTecchio/SharErasmus#34]
### Sviluppo
- [x] client
- [ ] server

### Ho sviluppato

- Visualizzazione dei post

### Devo ancora sviluppare
- Pubblicazione post
- Risposta ai post
- Bacheca avvisi
- Sistema di rating
- Sistema di tag, notifiche

**Comment by CiccioTecchio** [comment]
@peppeprown2 sei un pò indietro, cerca di fare il possibile. Al limite potremo affiancarti qualcuno appena si libera.
