### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Pcantarella7** [CiccioTecchio/SharErasmus#35]
### Sviluppo
- [x] server
- [ ] client
### Ho sviluppato    
-    Invio messaggi e salvataggio su Firebase;
### Devo ancora sviluppare 
-    Chat di gruppo;
-    Invio e ricezione messaggi in tempo reale;

**Comment by CiccioTecchio** [comment]
Cerca di ultimare quanto prima il lavoro perchè abbiamo bisogno di risorse sulle altre gestioni
