### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by fonzSJ** [CiccioTecchio/SharErasmus#39]
**Describe the bug**
this.targetKeyField = this.target.rawAttributes[this.targetKey].field || this.

TypeError: Cannot read property 'field' of undefined

Si sta stabilendo una relazione al contrario, penso che sia un problema di foreign-key.
È la riga commentata che vedi nello screenshot sottostante.

**Screenshots**
![issedavidecorretta](https://user-images.githubusercontent.com/44618581/50646290-fbb45300-0f75-11e9-8671-a8b52b4cca37.png)

**Comment by davide-bottiglieri** [comment]
Anche commentando quella riga mi da lo stesso errore

**Comment by davide-bottiglieri** [comment]
Bisogna provvedere a trovare una soluzione!

**Comment by davide-bottiglieri** [comment]
### Soluzione trovata!
#### Bisogna modificare i nomi degli attributi del model con gli attuali nomi presenti sul DB.
